### ISSUE TITLE
Update to jQuery Mobile 1.4

### ISSUE THREAD

**Issue by kryops** [kryops/jqm-inlinetabs#1]
mark 1.2 and 1.3 Version as Releases / tags

**Comment by danpaulsmith** [comment]
Hi Krypos,

Are you planning to update to jQM 1.4? Or have you already? inlinetabs is erroring on no "enhanceWithin" function

**Comment by kryops** [comment]
Hi Dan,

I'm not really sure if it's worth updating to 1.4 as it already has included a tab functionality by default now: http://demos.jquerymobile.com/1.4.2/tabs/

I haven't had time to try it out and decide yet...

**Comment by calql8tor** [comment]
Hi Krypos,

We really like the "look and feel" of the tabs which you have created.  If we have to switch to using navbar, can we achieve the "look and feel" via css?

Would it be hard to eliminate the "enhanceWithin" issue?

I have a young programmer on staff who has been using this for some time now and is wanting to upgrade to jqm 1.4.5.  

Navbar is ok, but your tabs were more intuitive!

Thanks in advance,
calql8tor

**Comment by kryops** [comment]
Hi calql8tor,

as I don't use jQuery Mobile for any current projects, I haven't had a look at the 1.4 API and CSS changes so I can't tell how difficult it would be to change the plugin yet.

Modifying the navbar via CSS shouldn't be a very hard problem. You can use the CSS classes that jQuery Mobile automatically adds to the elements. Just give the tab container a custom class:

``` html
<div data-role="tabs" id="tabs" class="inlinetabs">
```

and then you can play around with the CSS. My fast little try looked like this:

``` css
.inlinetabs .ui-navbar {
    padding: 0 8px;
}

.inlinetabs .ui-tabs-nav > li {
    margin: 0 2px;
    width: auto;
    clear: none;
}

.inlinetabs .ui-tabs-nav .ui-btn {
    border: 1px solid #ddd;
    border-bottom: none;
    border-top-left-radius: .6em;
    border-top-right-radius: .6em;
}

.inlinetabs .ui-tabs-panel {
    background: #fff;
    border-radius: .6em;
    border: 1px solid #ddd;
}
```
